In [1]:
import numpy as np

In [12]:
# How to increase a dimension
a = np.arange(20)
a2 = a[np.newaxis,:]
a2.shape

(1, 20)

In [14]:
a2 = a[:, np.newaxis]
print(a2)
a2.shape

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


(20, 1)

In [15]:
print(np.expand_dims(a, axis=1))

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [16]:
print(np.expand_dims(a, axis=0))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


In [18]:
np.reshape(a, (-1,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [19]:
np.reshape(a, (1,-1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [8]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [14]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [17]:
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1])

In [22]:
arr = np.array([0,1,5,9,4,7,5])
np.sort(arr)

array([0, 1, 4, 5, 5, 7, 9])

In [2]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a = np.array([[1,2], [3,4]])
b = np.array([[7,8]])
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [7, 8]])

In [5]:
arr_ex = np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [0,2,4,6],
        [1,3,5,7]
    ],
    [
        [0,4,8,12],
        [0,3,6,9]
    ]
])

arr_ex.shape

(3, 2, 4)

In [6]:
arr_ex.size

24

In [7]:
arr_ex.ndim

3

In [8]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [21]:
a = np.array([1,2,3,4,5])
a[a<5]

array([1, 2, 3, 4])

In [22]:
a[(a>2) & (a<5)]

array([3, 4])

In [23]:
np.nonzero(a<5) # returns the index of the element which satisfy the condition

(array([0, 1, 2, 3]),)

In [32]:
a = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
b = np.nonzero(a < 6)
print(b)
# First one indicate across the row indices where its found, second array represent the column indices where its found

(array([0, 0, 0, 0, 1]), array([0, 1, 2, 3, 0]))


In [33]:
list_of_cord = list(zip(b[0], b[1]))
print(*list_of_cord)

(0, 0) (0, 1) (0, 2) (0, 3) (1, 0)


In [34]:
a[b]

array([1, 2, 3, 4, 5])

In [36]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [38]:
a = np.arange(1,25).reshape(2,12)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [39]:
np.hsplit(a,3) # horizontal split in the 3rd column

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [40]:
np.hsplit(a, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [41]:
data = np.array([1,2])
ones = np.ones(2, dtype=np.int64)

data + ones

array([2, 3])

In [42]:
np.array([1,2,3,4]).sum()

10

In [43]:
a = np.array([[1,2],[3,4]])
a.sum(axis=1)

array([3, 7])

In [44]:
a.sum(axis=0)

array([4, 6])

In [45]:
data = np.array([[1,2],[3,4], [5,6]])
ones_row = np.array([[1,1]])

data + ones_row # broadcasting 

array([[2, 3],
       [4, 5],
       [6, 7]])

In [47]:
# generate random numbers
rng = np.random.default_rng()
rng.random((3,4))

array([[0.74091359, 0.55461184, 0.99937054, 0.98554222],
       [0.48963858, 0.41951226, 0.95709575, 0.92683897],
       [0.53243106, 0.48727299, 0.45584719, 0.44070606]])

In [49]:
a = np.array([1,1,2,2,3,3,4,5,6,7])
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
np.unique(a, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7]), array([2, 2, 2, 1, 1, 1, 1]))

In [51]:
np.unique(a, return_index=True)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 2, 4, 6, 7, 8, 9]))

In [56]:
a = np.arange(6).reshape((2,3))
print(a)
a.T


[[0 1 2]
 [3 4 5]]


array([[0, 3],
       [1, 4],
       [2, 5]])

In [59]:
# reverse an array
a = np.arange(6).reshape(3,2)
print(a)
np.flip(a)

[[0 1]
 [2 3]
 [4 5]]


array([[5, 4],
       [3, 2],
       [1, 0]])

In [61]:
np.flip(a,axis=0)

array([[4, 5],
       [2, 3],
       [0, 1]])

In [63]:
np.flip(a,axis=1)

array([[1, 0],
       [3, 2],
       [5, 4]])

In [65]:
a = np.arange(12).reshape(3,4)
a.flatten() # deep copy 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
a.ravel() # shall copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])